theme: jekyll-theme-minimal
title: Jon Debonis
description: The best security exists where people meet technology. I'm Jon Debonis and I help people achieve the best security. This is my resume, opinions, and projects.
url: https://redcar.io
author: jondebonis
twitter:
  username: jondebonis
  card: summary
logo: /assets/logo.jpg
social:
  name: Jon Debonis
  links:
    - https://twitter.com/jondebonis
    - https://www.linkedin.com/in/jondebonis
    - https://github.com/jondb
    - https://keybase.io/jondb


